[build]
  command = "pip install -r requirements.txt && python main.py"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/serverless"

[[functions]]
  name = "serverless"
  memory = 128
  timeout = 30
  runtime = "python3.9"
  max_duration = 60
  environment = { PYTHONUNBUFFERED = "true" }
  script = "main.py"
